version: '3.1'

services:

  wordpress:
    image: wordpress
    #restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: admin
      WORDPRESS_DB_PASSWORD: qwerty
      WORDPRESS_DB_NAME: wordpress_database
    volumes:
      - wordpress:/var/www/html

  db:
    image: mysql:5.7
    # restart: always
    environment:
      MYSQL_DATABASE: wordpress_database
      MYSQL_USER: admin
      MYSQL_PASSWORD: qwerty
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql

volumes:
  wordpress:
  db: